name: Linux CI Tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: sudo .github/scripts/install_software.sh
    - name: Build
      run: .github/scripts/build_repo.sh
